.TH GNUAN GNUCHESS
.SH NAME
gnuan
.SH SYNOPSIS
.B gnuan
.SH DESCRIPTION
.I gnuan
produces an analysis of a chess game.
For each move it shows the move, the score and the principle variation selected
by
.I gnuchess

.I gnuan
prompts for input parameters when it is invoked.
Input file is a
.I gnuchess
list file or a 
.I xboard 
game file or a
.I PGN
file.

.I gnuan is a modification of the gnuan program from
Truman Collins (tcollins@pdx.mentor.com).
.SH "FUNCTION LETTERS"
The following commands are recognized:
.PP
.B bd
-- Print out the current board
.PP
.B depth n
-- set depth to search
.PP
.B next
-- find the next best move in this position.
.PP
.B top n
-- find the best n moves (1<n<5) in each position.
.PP
.B quit
-- quit
.PP
.B n
-- where n is a number, go to move n. n must be forward from current position
.PP
.B var
-- enter a variation from the stored line. Return from the variation will go back to the current posution.
If you are in a variation you enter the moves and they are then evaluated.
.PP
.B rav
-- return from a variation.
.PP
.B go
-- advance 1 ply.

To emulate the old gnuan just type a number > number of moves at the command prompt. The moves
will be examined til the end of the game.

.SH BUGS
.PP
.fi
.SH SEE ALSO
.nf
gnuchess(6)
chesstool(6)
xboard(6)
.fi

