CC = gcc
obj = fib0 fib1 fib2 fib3 fib4 fibT
src = *.c

all: $(obj)

fib0: fibonacci0.c
	gcc fibonacci0.c -o fib0

fib1: fibonacci1.c
	gcc fibonacci1.c -o fib1

fib2: fibonacci2.c
	gcc fibonacci2.c -o fib2

fib3: fibonacci3.c
	gcc fibonacci3.c -o fib3

fib4: fibonacci4.c
	gcc fibonacci4.c -o fib4

fibT: fibonacciT.c
	gcc fibonacciT.c -o fibT

clean:
	rm -f $(obj)
