CC   = gcc
TGTS = fib0 fib1 fib2 fib3 fib4 fibT
SRCS = *.c

all: $(TGTS)

fib0: fibonacci0.c
	$(CC) fibonacci0.c -o fib0

fib1: fibonacci1.c
	$(CC) fibonacci1.c -o fib1

fib2: fibonacci2.c
	$(CC) fibonacci2.c -o fib2

fib3: fibonacci3.c
	$(CC) fibonacci3.c -o fib3

fib4: fibonacci4.c
	$(CC) fibonacci4.c -o fib4

fibT: fibonacciT.c
	$(CC) fibonacciT.c -o fibT

clean:
	rm -f $(TGTS)
