obj = btree list permute sort sortins sortmerge sortsel
src = *.c *.h

all: btree list permute random reverse sort sortins sortmerge sortsel

btree: btree.h btree.c
	gcc btree.c -Wreturn-type -o btree

list: list.h list.c
	gcc list.c -o list

permute:
reverse:
sort:
sortins:
sortmerge:
sortsel:

clean:
	rm -f $(obj)
